# Creates the update-signing key pair.
#
#   * PRIVATE key  -> %USERPROFILE%\.netvigil\update-signing-key.dpapi
#                     encrypted with DPAPI for the current Windows user, so only
#                     this account on this machine can use it. Never committed.
#   * PUBLIC key   -> src\update_pubkey.h (committed; baked into NetVigil.exe).
#
# Losing the private key means installed copies can never be updated again
# (they only trust this public key). The .dpapi file only decrypts for you on
# this PC, so a copy of it is NOT an off-machine backup: if you need one, mint a
# new key with -Force before shipping, and ship a release that carries the new
# public key while the old key still exists.
#
# Usage: pwsh -File tools\new-signing-key.ps1 [-Force]
param([switch]$Force)
$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Security.Cryptography.ProtectedData

$keyDir  = Join-Path $env:USERPROFILE '.netvigil'
$keyFile = Join-Path $keyDir 'update-signing-key.dpapi'
$header  = Join-Path $PSScriptRoot '..\src\update_pubkey.h'

if ((Test-Path $keyFile) -and -not $Force) {
    throw "A signing key already exists at $keyFile. Replacing it strands every installed copy; pass -Force only if you mean it."
}

$ec = [System.Security.Cryptography.ECDsa]::Create(
        [System.Security.Cryptography.ECCurve]::CreateFromFriendlyName('nistP256'))
$p = $ec.ExportParameters($true)
if ($p.D.Length -ne 32 -or $p.Q.X.Length -ne 32 -or $p.Q.Y.Length -ne 32) { throw 'unexpected key size' }

# D || X || Y, DPAPI-protected (current user), with a fixed entropy string.
$secret  = [byte[]]($p.D + $p.Q.X + $p.Q.Y)
$entropy = [Text.Encoding]::ASCII.GetBytes('netvigil-update-signing-key-v1')
$blob    = [System.Security.Cryptography.ProtectedData]::Protect(
              $secret, $entropy, [System.Security.Cryptography.DataProtectionScope]::CurrentUser)
New-Item -ItemType Directory -Force -Path $keyDir | Out-Null
[IO.File]::WriteAllBytes($keyFile, $blob)
[Array]::Clear($secret, 0, $secret.Length)

# Public key as an uncompressed X9.62 point: 0x04 || X || Y (65 bytes).
$pub = [byte[]](@(0x04) + $p.Q.X + $p.Q.Y)
$lines = for ($i = 0; $i -lt $pub.Length; $i += 13) {
    '    ' + (($pub[$i..([Math]::Min($i + 12, $pub.Length - 1))] | ForEach-Object { '0x{0:x2}' -f $_ }) -join ', ') + ','
}
$fp = [BitConverter]::ToString([Security.Cryptography.SHA256]::HashData($pub)).Replace('-', '').Substring(0, 16).ToLower()
@"
// GENERATED by tools\new-signing-key.ps1 — do not edit by hand.
// ECDSA P-256 public key (uncompressed X9.62 point) that update manifests must
// be signed with. The private half never leaves the maintainer's PC.
// Fingerprint (SHA-256 of the point, first 8 bytes): $fp
#pragma once

static const unsigned char kUpdatePubKey[65] = {
$($lines -join "`n")
};
"@ | Set-Content -Path $header -Encoding utf8

Write-Host "private key : $keyFile  (DPAPI, current user only)"
Write-Host "public key  : $((Resolve-Path $header).Path)"
Write-Host "fingerprint : $fp"
